#!/bin/sh
# one command to copy all source files from development directory to another ready for .tar.gz'ing etc.

cp ../DEVEL/*.[ch] .
cp ../DEVEL/README .
cp ../DEVEL/LICENSE .
cp ../DEVEL/Makefile .

if [ "$2" != "gui" ]; then
    rm gui*
    cp ../DEVEL/Makefile .
else
    cp ../DEVEL/Makefile.gui Makefile
fi

if [ "$1" = "bin" ]; then
   # Build binary and remove all source code
   make
   rm *.[cho]
   rm -f hc.make.cli
   rm -f hc.make.gui
   rm Makefile
fi
