#!/bin/sh
# one command to copy all source files from development directory to another ready for .tar.gz'ing etc.

cp ../DEVEL/*.[ch] .
cp ../DEVEL/README .
cp ../DEVEL/LICENSE .
mkdir qtgui
cp ../DEVEL/qtgui/*.[ch]pp qtgui/
cp ../DEVEL/qtgui/hcg.rc qtgui/
cp ../DEVEL/qtgui/qtgui.pro qtgui/

if [ "$2" != "gui" ]; then
    rm -r qtgui/
    cp ../DEVEL/Makefile .
else
    rm main.c
fi

if [ "$1" = "bin" ]; then
   if [ "$2" != "gui" ]; then
   # Build binary and remove all source code
       make
       rm *.[cho]
       rm -f hc.make.cli
       rm -f hc.make.gui
       rm Makefile
   else
       cd qtgui
       qmake
       make
       mv HCG ..
       cd ..
       rm -r qtgui
       rm *.[cho]
   fi
fi
